version: '3.8'

services:
  app:
    image: ahmednaifer/tp-foyer:1.0.0
    container_name: tp-foyer-app
    hostname: app
    ports:
      - "8087:8089"
    environment:
      SPRING_MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE: "*"
      SPRING_MANAGEMENT_ENDPOINTS_WEB_BASE_PATH: /actuator
      SPRING_MANAGEMENT_ENDPOINT_HEALTH_SHOWDETAILS: always
      # Database configuration
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/db?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD:
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    depends_on:
      - db
    networks:
      - monitoring

  db:
    container_name: postgres-db
    image: postgres
    environment:
      POSTGRES_USER: ahmed
      POSTGRES_PASSWORD: ahmed
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: db
    volumes:
      - postgres:/data/postgres
    ports:
      - '5432:5432'
    networks:
      - spring-demo
    restart: unless-stopped

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - '9090:9090'
    depends_on:
      - app
    networks:
      - monitoring

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - '3000:3000'
    volumes:
      - grafana-data:/var/lib/grafana
    networks:
      - monitoring

volumes:
  grafana-data:
    driver: local

networks:
  monitoring:
    driver: bridge